deis/docker-go-dev

- Makefile
- rootfs/Dockerfile
fwiw, the need for a newer version of this that support golint is blocking upcoming router PRs.
> feat(image): add golint and bump version

- rootfs/Dockerfile
`RUN` commands for a given task (i.e. installing a package) should be grouped into one layer.
This improves the style in two ways: Developers can at a single glance say "OK, this group of commands install _glide_"; And, of course, we get a smaller number of layer per image.
> style(Dockerfile): Squash glide RUN commands into one layer

- rootfs/Dockerfile
I'd also like us to consider tagging this as a `0.3.0` feature release after this is merged.  Why a feature release?  Because glide 0.8.0+ has support for `glide.lock` files and that new glide feature constitutes a new capability for this image-- one that I think people would like to start using.
> feat(Dockerfile): upgrade to glide version 0.8.1

- Makefile
This change matches what other deis repos do, and keeps the build environment consistent.
cc/ @krancour
> ref(Makefile): remove trailing slash from IMAGE_PREFIX

- rootfs/Dockerfile
This replaces the older, 0.8.3 version of [glide](https://github.com/Masterminds/glide) with the newer [0.9.0 Release Candidate 1 version](https://github.com/Masterminds/glide/releases/tag/0.9.0-rc1)
> chore(rootfs/Dockerfile): upgrade to glide 0.9.0-RC 1

- rootfs/Dockerfile
Adds zip since that's generally useful in an environment where things are being built-- as there's a high likelihood of needing to archive and/or compress built things.  In particular, a containerized build of helm would benefit from having this available.  See https://github.com/helm/helm/issues/397
> feat(image): Add zip package

- rootfs/Dockerfile
Some of the projects that are using this image to containerize their builds and various other make targets sometimes include a target like `make dev` or `make dev-env` that drops a developer interactively at a prompt within the container...
`man` is simply a generally useful tool to have available to developers who may at times step into the containerized dev environment as described above.
> feat(image): Add man package

- README.md
- rootfs/Dockerfile
It is [no longer needed](https://github.com/pwaller/goupx#update-20160310) as `upx` can handle go 1.6 binaries.
> chore(Dockerfile): remove goupx for go 1.6+

- .travis.yml
The `deploy` step has been consistently skipped because Travis reports
> Skipping a deployment with the script provider because this branch is not permitted
I think this will fix it based on other Workflow repository configs that were working.
> fix(.travis.yml): allow deploy on git tags

- Makefile
- README.md
- rootfs/usr/local/bin/gen-changelog.sh
This more flexible version in the standard go-dev image lets components remove the copy-pasted `_scripts/generate-changelog.sh`.
Add a Makefile target and go:
```Makefile
gen-changelog:
${DEV_ENV_CMD} gen-changelog.sh
```
```console
$ make gen-changelog
docker run --rm -e GO15VENDOREXPERIMENT=1 -v /Users/matt/Projects/src/github.com/deis/builder:/go/src/github.com/deis/builder -w /go/src/github.com/deis/builder quay.io/deis/go-dev:latest gen-changelog.sh
- [`514d0e3`](https://github.com/deis/builder/commit/514d0e3f604de5ddb2450d0b7a5b5729325573e8) pkg/sshd: Store private keys in kubernetes secret
- [`1c37d86`](https://github.com/deis/builder/commit/1c37d86feae5925f430c2825c81abc5104cc1453) sshd: log incoming env request to debug level
- …
```
> feat(gen-changelog.sh): add CHANGELOG.md generator

- .travis.yml
- Makefile
- README.md
- rootfs/usr/local/bin/test-cover.sh
This adapts the [script recommended by codecov.io](https://github.com/codecov/example-go#caveat-multiple-files) to use `glide novendor` and to pass `shellcheck`. 
`test-cover.sh` can be called from project Makefiles to run tests recursively and concatenate a master `coverage.txt` file. For example, add it to a Makefile target:
```Makefile
test-cover:
${DEV_ENV_CMD} test-cover.sh
```
Then add `coverage.txt` to `.gitignore` and invoke test-cover:
```console
$ make test-cover
docker run --rm -e GO15VENDOREXPERIMENT=1 -v /Users/matt/Projects/src/github.com/deis/builder:/go/src/github.com/deis/builder -w /go/src/github.com/deis/builder quay.io/deis/go-dev:latest test-cover.sh
?   	github.com/deis/builder/pkg	[no test files]
ok  	github.com/deis/builder/pkg/cleaner	5.017s	coverage: 84.6% of …
```
> feat(test-cover.sh): add go code coverage test script

- rootfs/Dockerfile
This should allow the jenkins user to actually delete the files created by the docker container.
I don't have ssh access to the build slaves, but this is identical to work done in places like deis/docker-shell-dev.
Ping @vdice @jchauncey, who have experience with this.
> fix(dockerfiles): create files with same uid as jenkins

- rootfs/Dockerfile
This turned out to be brittle on computers that aren't jenkins (like developers machine).
> fix(dockerfiles): revert create files with same uid as jenkins

- rootfs/Dockerfile
- rootfs/usr/local/bin/lint
[Gometalinter](https://github.com/alecthomas/gometalinter) is a linter that combines the most popular linters together.
It contains the linters we already use: `go vet`, `gofmt`, and `golint`, but also many more useful ones, such as the ones used by [goreportcard](https://goreportcard.com/report/github.com/deis/controller-sdk-go). It also runs them in parallel, so it shouldn't incur a large performance penalty.
It also prints out standardized output for all linters and returns error codes, so we don't have to use the hacks we use with gofmt to get a proper error code. It's also smart about the input format of packages, so we can just run `gometalinter ./...` and not have to worry about keeping lists of packages and go files to run the linter on, reducing makefile maintenance.
> Proposal: feat(linters): switch to gometalinter

- rootfs/usr/local/bin/lint
Since you can't see the linter commands run, it's pretty hard to tell the difference between mandatory or recommended linters.
> feat(lint): differentiate between manadatory and optional linters

- rootfs/Dockerfile
This allows us to share the same base image as everything else. In addition, the `golang` image wasn't very slimed down, so we shrink size from 294 MB -> 180 MB
> feat(Dockerfile): base off deis/base

- rootfs/Dockerfile
I'd like to include k8s-claimer in the toolbox for easy use by any of our own projects that have a specific need to lease a cluster to facilitate e2e or integration tests.
cc @mboersma @arschles
> feat(k8s-claimer): Add latest k8s-claimer to the toolbox

- rootfs/Dockerfile
Some useful tools were inadvertently lost when refactoring to [use deis/docker-base](https://github.com/deis/docker-go-dev/pull/52).
See #58 for a different approach to fixing this.
> ref(Dockerfile): revert to golang:1.7.1 base image

- rootfs/Dockerfile
Steward and Pilot will both find this useful as both are using (or will use) GRPC. This adds 13.4 MB to the image.
cc @arschles
> feat(image): Add protoc and protoc-gen-go to image

- rootfs/Dockerfile
Also moves the `shellcheck` binary to Azure blob storage.
> feat(Dockerfile): update shellcheck to v0.4.6

- rootfs/Dockerfile
This utility is used on the ACS RP team for now to build all of their binaries. Adding it to this image lets me start containerizing their build
> feat(gb): Adds the gb utility to the image

- rootfs/Dockerfile
Automates the collation of individual `go test -cover` files, which go itself still can only handle one package at a time.
> feat(Dockerfile): add goverage code coverage collation tool

- rootfs/Dockerfile
Adding the openssh client so this image can ssh into other things and generate ssh keys. This will be used particularly for the acs-engine e2e tests.
> feat(rootfs/Dockerfile): Add openssh-client

- rootfs/Dockerfile
See https://github.com/Masterminds/glide/releases/tag/v0.13.0
The latest version of `dep` is also built into this image, btw.
> chore(rootfs/Dockerfile): update glide to 0.13.0

- rootfs/Dockerfile
Pulling from master is considered dangerous for the `dep` vendoring tool, according to @carolynvs and the project's [README](https://github.com/golang/dep#installation). Currently this fetches v0.4.1:
```console
$ docker run -it quay.io/deis/go-dev:local dep version
dep:
version     : v0.4.1
build date  : 2018-01-24
git hash    : 37d9ea0a
go version  : go1.9.1
go compiler : gc
platform    : linux/amd64
```
> chore(Dockerfile): use latest released version of `dep`

- rootfs/Dockerfile
Adds the newer, stable version of `gometalinter` as [recommended](https://github.com/alecthomas/gometalinter#installing). Note that the binary is called `gometalinter.v2`.
> chore(roots/Dockerfile): add stable gometalinter.v2

- rootfs/Dockerfile
This is the recommended installation according to the author. The `go get` version is currently broken when trying to do `make build` of this Docker image.
> chore(roots/Dockerfile): use binary release for gometalinter

- rootfs/Dockerfile
Installing from a pre-packaged version of `gometalinter` eventually caused a problem when `go` was upgraded to 1.11 since `goimports` needed to be recompiled. This changes the install method to use the latest stable tag for `gometalinter` and lets `gometalinter --install` fetch and compile `goimports` and friends.
Refs Azure/acs-engine#3763.
> chore(rootfs/Dockerfile): install gometalinter from stable tag

- rootfs/Dockerfile
Because this image is often used in build environments, it's useful to be able to exclude it from things like `docker system prune` by using the `--filter` flag which works on labels. This way, your build system always has the go-dev image available but you still prune old images no longer being used.
> feat(dockerfile): add a label to the dockerfile

- rootfs/Dockerfile
Includes support pushing helm packages with path reference
See: https://github.com/Azure/azure-cli/releases/tag/azure-cli-2.0.46
> chore(az): update az cli to 2.0.46

- rootfs/Dockerfile
See https://golang.org/doc/devel/release.html#go1.11.minor
> chore(rootfs/Dockerfile): update go toolchain to 1.11.2

- rootfs/Dockerfile
The helm client hasn't been updated in almost a year, because it needed to stay at the same version as tiller servers in our main use case. Building from source bypasses the strict version check so that `helm` can be used against most versions of tiller.
```
$ docker run quay.io/deis/go-dev:latest helm version
Client: &version.Version{SemVer:"v2.12+unreleased", GitCommit:"", GitTreeState:"clean"}
```
Closes #98.
> Build helm client from source

- rootfs/Dockerfile
This PR fixes #123 
>Golangci-lint is a faster version of gometalinter and provides more features as well.
>https://github.com/golangci/golangci-lint#performance
The current linting implementation uses gometalinter which has performance disadvantages over golangci-lint. They claim it's down to 'calling the linters directly and reuses work by the parsing program once'. 
From a bit of investigation I have seen it *is* faster. I tried on various projects and saw some good performance improvements. However, they also need to do quite a bit more work with program load times as that's still where the current bottleneck is imo, probably should look into disk cache or something.
Running lint on a current up-to-date fork of the acs-engine repository I got the following:
```
golang-ci
real …
```
> Migrate linting to use golangci-lint

- rootfs/Dockerfile
This version of golangci-lint has import false positive fixes for the `unused` linter.
For more details check : https://github.com/golangci/golangci-lint/releases/tag/v1.11.3
> update to the latest patch release of golangci-lint 1.11

- rootfs/Dockerfile
Removes over 2GB of cached files that were inadvertently built into the Docker image.
```
$ docker images
REPOSITORY             TAG            IMAGE ID        CREATED              SIZE
quay.io/deis/go-dev    before         e8aed44f9cea    5 days ago           3.94GB
quay.io/deis/go-dev    after          2d2b1553095e    About a minute ago   1.82GB
```
> chore(rootfs/Dockerfile): remove cached files

- rootfs/Dockerfile
Shellcheck doesn't seem to exist in `https://deisbuildartifacts.blob.core.windows.net/`.
This PR fixes that by downloading via `apt-get` instead.
> fix: download shellcheck from the apt-get repo

- rootfs/Dockerfile
Installs the latest version of the `shellcheck` binary from their GitHub artifacts.
In #156 we inadvertently regressed the version of `shellcheck` (to v0.3.7 from v0.4.6) because the latest version packaged for Ubuntu is ancient.
> chore(rootfs/Dockerfile): update shellcheck to v0.6.0

- rootfs/Dockerfile
> chore(rootfs/Dockerfile): update go toolchain to 1.12.4

- rootfs/Dockerfile
Helm was being installed via source. When using helm in this way it will print a warning message about using an unreleased version. This fixes that issue.
I also removed the k8s-claimer download which is no longer needed.
cc @mboersma
> fix: Install helm via the release tarball

- rootfs/Dockerfile
> chore(rootfs/Dockerfile): update go toolchain to 1.12.5

- rootfs/Dockerfile
> chore(rootfs/Dockerfile): update go toolchain to 1.12.6

- rootfs/Dockerfile
> chore(rootfs/Dockerfile): update go toolchain to 1.12.7

- rootfs/Dockerfile
> chore(rootfs/Dockerfile): update go toolchain to 1.12.8

- rootfs/Dockerfile
> chore(rootfs/Dockerfile): update go toolchain to 1.12.9

- rootfs/Dockerfile
> chore(rootfs/Dockerfile): update go toolchain to 1.12.10

- rootfs/usr/local/bin/k
See https://github.com/jakepearson/k/pull/5
The merge is needed because docker-go-dev has some tweaks to `k` that haven't made it upstream:
- silent output so as not to upset CI
- fallback `kubectl` version instead of erroring
> chore(rootfs/Dockerfile): update k with recent changes

- rootfs/Dockerfile
> chore(rootfs/Dockerfile): update go toolchain to 1.12.12

- rootfs/Dockerfile
> chore(rootfs/Dockerfile): update go toolchain to 1.12.13

- rootfs/Dockerfile
> chore(rootfs/Dockerfile): update go toolchain to 1.12.14

- README.md
The HTTPS URL version doesn't redirect to Azure AKS AFAICT, so let's stop referring to it.
> docs(README.md): don't reference dead deis.com site

- rootfs/Dockerfile
See https://golang.org/doc/devel/release.html#go1.13.minor
> chore(rootfs/Dockerfile): update go toolchain to 1.13.6

- rootfs/Dockerfile
This looks like a necessary precursor to updating golangci-lint and the go toolchain. Otherwise I seem to run into compile errors.
> refactor(rootfs/Dockerfile): install shfmt from binary

- rootfs/Dockerfile
This requires using `pip3`. Installing az-cli 2.3.x fails with 
```
Collecting mock~=4.0 (from azure-cli)
Could not find a version that satisfies the requirement mock~=4.0 (from azure-cli) (from versions: 0.5.0, 0.6.0, 0.7.0b1, 0.7.0b2, 0.7.0b3, 0.7.0b4, 0.7.0rc1, 0.7.0, 0.7.1, 0.7.2, 0.8.0, 1.0b1, 1.0.0, 1.0.1, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.2.0, 1.3.0, 2.0.0, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5)
No matching distribution found for mock~=4.0 (from azure-cli)
```
According to https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?view=azure-cli-latest#prerequisites, "The CLI has dropped support for Python 2.7 since version 2.1.0. New versions no longer guarantee to run with Python 2.7 correctly."
> chore(rootfs/Dockerfile): update Azure CLI to 2.3.1

- rootfs/Dockerfile
See https://github.com/golang/go/issues?q=milestone%3AGo1.14.2+label%3ACherryPickApproved
> chore(rootfs/Dockerfile): update go toolchain to 1.14.2

- rootfs/Dockerfile
Retain python3-pip package so that az extensions can be added.
Example: `az extension add --name azure-devops`
Fixes #227.
> chore(rootfs/Dockerfile): retain python3-pip in the image

- rootfs/Dockerfile
See https://github.com/golang/go/issues?q=milestone%3AGo1.14.3+label%3ACherryPickApproved
> chore(rootfs/Dockerfile): update go toolchain to 1.14.3

- rootfs/Dockerfile
See https://github.com/golang/go/issues?q=milestone%3AGo1.14.4+label%3ACherryPickApproved
> chore(rootfs/Dockerfile): update go toolchain to 1.14.4

- rootfs/Dockerfile
See https://github.com/golang/go/issues?q=milestone%3AGo1.14.6+label%3ACherryPickApproved
> chore(rootfs/Dockerfile): update go toolchain to 1.14.6

- rootfs/Dockerfile
Kubernetes 1.19.0-rc.3 is building with this, so let's get on that train.
> chore(rootfs/Dockerfile): update go toolchain to 1.15rc1

- rootfs/Dockerfile
See https://github.com/golang/go/issues?q=milestone%3AGo1.15.1+label%3ACherryPickApproved
> chore(rootfs/Dockerfile): update go toolchain to 1.15.1

- rootfs/Dockerfile
See https://github.com/golang/go/issues?q=milestone%3AGo1.15.2+label%3ACherryPickApproved
> chore(rootfs/Dockerfile): update go toolchain to 1.15.2

- rootfs/Dockerfile
Letting the packer version float seems finally to have caused problems in Azure/aks-engine#3879. This pins it at the last-known-working version for AKS Engine, 1.6.1.
> fix: pin Hashicorp packer at 1.6.1

- rootfs/Dockerfile
[Image-builder](https://github.com/kubernetes-sigs/image-builder/blob/master/images/capi/hack/ensure-ansible.sh) expects to use python3 as the ansible interpreter and modules are installed there.  This installs ansible via pip which is recommended for getting python3 support: https://docs.ansible.com/ansible/latest/reference_appendices/python_3_support.html#on-the-controller-side  
This also adds the winrm python module needed for windows images via image builder
/cc @mboersma @CecileRobertMichon
> Use pip to install ansible for python3 interpreter

- rootfs/Dockerfile
Signed-off-by: Ernest Wong <chuwon@microsoft.com>
Also need to specify `PyJWT` version since Azure CLI will install `PyJWT` 2.0.0, which breaks `az login -i`.
> chore(rootfs/Dockerfile): update Azure CLI version to 2.17.1

- rootfs/Dockerfile
> chore(rootfs/Dockerfile): use official go-delve/delve debugger

- README.md
- rootfs/Dockerfile
Fixes #257
Note that AKS Engine still relies on `go-bindata`, so that needs to stay. Helm 3 replaced 2 in #262.
> chore(rootfs/Dockerfile): remove deprecated Go projects

- rootfs/Dockerfile
- rootfs/usr/local/bin/lint
- update base image to `ubuntu:20.04` focal lts
- switch to `golangci-lint` for linter as `gometalinter` is DEPRECATED
- `golint` is DEPRECATED in favor of drop-in replacement `revive`
- enable `typecheck` linter as mandatory (pretty quiet linter)
- enable `gosec`, `gocritic`, and `gocognit` as optional linters
(useful)
- drop library `libicu60` for library `libc6` that exists in focal
Signed-off-by: Cryptophobia <aouzounov@gmail.com>
> chore(Dockerfile): updates from team hephy

- rootfs/Dockerfile
Had to do some thrashing around to find a packaged ansible that fixes all the issues around `ansible.windows` and cloud-init. This seems to work, as tested on an internal Azure pipeline.
cc: @jsturtevant
> fix(rootfs/Dockerfile): update ansible to 4.2.0 to fix windows

- rootfs/Dockerfile
This seems to have broken since the last time we did a go-dev release:
```shell
% docker run -it ubuntu:20.04 bash
root@c8b90ef772d4:/# apt-get update && apt-get install yq 
Get:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease [265 kB]
Get:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease [114 kB]
Get:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease [101 kB]
Get:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease [114 kB]
Get:5 http://ports.ubuntu.com/ubuntu-ports focal/universe arm64 Packages [11.1 MB]
Get:6 http://ports.ubuntu.com/ubuntu-ports focal/restricted arm64 Packages [1317 B]
Get:7 http://ports.ubuntu.com/ubuntu-ports focal/multiverse arm64 Packages [139 kB]
Get:8 http://ports.ubuntu.com/ubuntu-ports focal/main arm64 Packages [1234 …
```
> chore(rootfs/Dockerfile): remove yq tool

- rootfs/Dockerfile
Hi!
The Dockerfile placed at "rootfs/Dockerfile" contains the best practice violation [DL3015](https://github.com/hadolint/hadolint/wiki/DL3015) detected by the [hadolint](https://github.com/hadolint/hadolint) tool.
The smell DL3015 occurs when the apt tool is used to install packages without the "--no-install-recommends" flag. This flag is recommended to be used to avoid installing additional packages not explicitly requested.
In this pull request, we propose a fix for that smell generated by our fixing tool. We have verified that the patch is correct before opening the pull request.
To fix this smell, specifically, the "--no-install-recommends" flag is added to the apt-get install command.
This change is only aimed at fixing that specific smell. If the fix is not valid or useful, please …
> Fix for Dockerfile smell DL3015

- rootfs/Dockerfile
Hi!
`install.goreleaser.com` [was deprecated a long time ago](https://goreleaser.com/deprecations/#godownloader) and now it's completely removed:
```
$ curl install.goreleaser.com
curl: (6) Could not resolve host: install.goreleaser.com
```
As a result, the `latest` image doesn't contain `golangci-lint` anymore:
```
$ docker run -it --rm quay.io/deis/go-dev:latest golangci-lint --version
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "golangci-lint": executable file not found in $PATH: unknown.
```
For example, one of old images:
```
$ docker run -it --rm quay.io/deis/go-dev:v1.34.4 golangci-lint --version
golangci-lint has version 1.44.0 built from …
```
> fix(rootfs/Dockerfile): update golangci-lint installation script

- README.md
- rootfs/Dockerfile
since the goss developer repository was changed (goss-org/goss) and to avoid repojacking
> goss dev's repo was changed
