deis/docker-go-dev

- rootfs/Dockerfile
Partial fix for https://github.com/deis/workflow/issues/139
cc/ @krancour
> feat(Dockerfile): add ginkgo CLI to the image

- rootfs/Dockerfile
> chore(Dockerfile): update glide to version 0.8.3

- rootfs/Dockerfile
See https://github.com/Masterminds/glide/releases/tag/0.9.1
> chore(rootfs/Dockerfile): upgrade to glide 0.9.1

- README.md
> docs(README.md): list other batteries included

- rootfs/Dockerfile
See https://github.com/Masterminds/glide/releases/tag/0.9.2
and https://github.com/Masterminds/glide/releases/tag/0.9.3
> chore(rootfs/Dockerfile): upgrade to glide 0.9.3

- rootfs/Dockerfile
See https://github.com/Masterminds/glide/releases/tag/0.10.0
and https://github.com/Masterminds/glide/releases/tag/0.10.1
> chore(rootfs/Dockerfile): upgrade to glide 0.10.1

- rootfs/Dockerfile
This is useful for facilitating development of helm-- which has make targets that utilize `jq`.  See open helm issue https://github.com/helm/helm/issues/397
> feat(image): Add jq package

- rootfs/Dockerfile
See https://github.com/deis/router/pull/162#issuecomment-209522319
Note that this PR also refactors the Dockerfile a little bit to be more compact, with fewer layers in the final image.
> feat(image): Add shellcheck

- rootfs/Dockerfile
See https://github.com/Masterminds/glide/releases/tag/0.10.2
> chore(rootfs/Dockerfile): upgrade to glide 0.10.2

- README.md
This says what deis/go-dev is for in simpler language and also adds some relevant hyperlinks.
> docs(README.md): update introductory wording

- README.md
> docs(README): add link to jq

- rootfs/Dockerfile
See https://github.com/Masterminds/glide/releases/tag/v0.11.0
> chore(rootfs/Dockerfile): upgrade to glide v0.11.0

- rootfs/Dockerfile
See https://github.com/Masterminds/glide/releases/tag/v0.11.1
> chore(rootfs/Dockerfile): upgrade to glide v0.11.1

- rootfs/Dockerfile
See https://github.com/Masterminds/glide/releases/tag/v0.12.1
> chore(rootfs/Dockerfile): upgrade to glide v0.12.1

- rootfs/Dockerfile
See https://github.com/golang/go/issues?q=milestone%3AGo1.7.1
Refs deis/workflow-cli#240
> chore(Dockerfile): update go toolchain to 1.7.1

- rootfs/Dockerfile
See https://github.com/Masterminds/glide/releases/tag/v0.12.2
> chore(Dockerfile): update glide to 0.12.2

- rootfs/Dockerfile
See https://github.com/Masterminds/glide/releases/tag/v0.12.3
> chore(Dockerfile): update glide to 0.12.3

- rootfs/Dockerfile
See https://github.com/golang/go/issues?q=milestone%3AGo1.7.3
> chore(Dockerfile): update go toolchain to 1.7.3

- rootfs/Dockerfile
See https://github.com/golang/go/issues?q=milestone%3AGo1.7.5
> chore(Dockerfile): update go toolchain to 1.7.5

- rootfs/Dockerfile
See https://github.com/golang/go/issues?q=milestone%3AGo1.8.1
> chore(Dockerfile): update go toolchain to 1.8.1

- rootfs/Dockerfile
See https://github.com/golang/go/issues?q=milestone%3AGo1.8.3
> chore(Dockerfile): update go toolchain to 1.8.3

- README.md
- rootfs/Dockerfile
Install Docker version: 17.05.0-ce in the image for use in a dev environment (to be able to mount a repo and running Docker commands).
> (DockerFile): Install Docker in the image

- README.md
- rootfs/Dockerfile
This enables the container to be used as a more complete development environment, which will help us with doing some tasks on Windows in particular.
> feat(Dockerfile): add helm and kubectl

- rootfs/Dockerfile
See https://blog.golang.org/go1.9
> chore(rootfs/Dockerfile): update go toolchain to 1.9

- rootfs/Dockerfile
See https://github.com/golang/go/issues?q=milestone%3AGo1.9.1
> chore(rootfs/Dockerfile): update go toolchain to 1.9.1

- rootfs/Dockerfile
See https://github.com/golang/go/issues?q=milestone%3AGo1.9.2
> chore(rootfs/Dockerfile): update go toolchain to 1.9.2

- rootfs/Dockerfile
See https://github.com/Masterminds/glide/releases/tag/v0.13.1
> chore(rootfs/Dockerfile): update glide to 0.13.1

- rootfs/Dockerfile
See https://github.com/golang/go/issues?q=milestone%3AGo1.9.3
> chore(rootfs/Dockerfile): update go toolchain to 1.9.3

- README.md
We missed a few in the README, this brings things more up-to-date.
> chore(README.md): detail other tools included in this image

- rootfs/Dockerfile
See https://github.com/golang/go/issues?q=milestone%3AGo1.9.4
> chore(rootfs/Dockerfile): update go toolchain to 1.9.4

- rootfs/Dockerfile
See https://golang.org/doc/go1.10
> chore(rootfs/Dockerfile): update go toolchain to 1.10

- rootfs/Dockerfile
See https://github.com/golang/go/issues?q=milestone%3AGo1.10.1
> chore(rootfs/Dockerfile): update go toolchain to 1.10.1

- Makefile
- rootfs/Dockerfile
This allows us to convert the coverage report generated by go to Cobertura
> add gocov tool

- README.md
- rootfs/Dockerfile
Adding ruby for container, useful if you are working on fluentd plugins.
> adding ruby

- README.md
- rootfs/Dockerfile
The deis/base image really isn't maintained.
> ref(Dockerfile,README): rebase image on Ubuntu:16.04

- rootfs/Dockerfile
See https://github.com/golang/go/issues?q=milestone%3AGo1.10.2
> chore(rootfs/Dockerfile): update go toolchain to 1.10.2

- README.md
- rootfs/Dockerfile
Also clean up Dockerfile and README.md.
> chore(rootfs/Dockerfile): add go-bindata tool

- README.md
- rootfs/Dockerfile
See https://github.com/hashicorp/packer
> feat(roots/Dockerfile): add Packer

- README.md
- rootfs/Dockerfile
> feat(rootfs/Dockerfile): add unzip archive utility

- rootfs/Dockerfile
See https://golang.org/doc/devel/release.html#go1.11.minor
> chore(rootfs/Dockerfile): update go toolchain to 1.11.4

- README.md
Updating the Readme.MD to include golangci-lint
> update docs to include golangci-lint

- README.md
- rootfs/usr/local/bin/k
See https://github.com/jakepearson/k
I made a couple changes that I will PR upstream:
- default to v1.10.12
- silence curl progress and print "Downloading kubectl v1.10.12..."
cc: @jakepearson @tariq1890
> feat(/usr/local/bin/k): Install kubectl just-in-time

- rootfs/Dockerfile
See https://golang.org/doc/go1.12
> chore(rootfs/Dockerfile): update go toolchain to 1.12

- rootfs/Dockerfile
See https://github.com/golang/go/issues?q=milestone%3AGo1.12.1
> chore(rootfs/Dockerfile): update go toolchain to 1.12.1

- README.md
- rootfs/Dockerfile
This allows adding `/usr/share/dict/words` used to randomize name in some scripts
> Add wamerican tool

- rootfs/Dockerfile
See https://github.com/Azure/azure-storage-azcopy/releases
Fixes #139
> feat(rootfs/Dockerfile): add azcopy v10 preview as `azcopy-preview`

- rootfs/Dockerfile
See https://github.com/golang/go/issues?q=milestone%3AGo1.12.2
> chore(rootfs/Dockerfile): update go toolchain to 1.12.2

- rootfs/Dockerfile
See https://github.com/golang/go/issues?q=milestone%3AGo1.12.3
> chore(rootfs/Dockerfile): update go toolchain to 1.12.3

- README.md
- rootfs/Dockerfile
Adds the latest stable release of [`shfmt`](https://github.com/mvdan/sh), the shell script formatter and minifier written in Go.
> feat(rootfs/Dockerfile): add shfmt shell formatter

- rootfs/Dockerfile
See https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?view=azure-cli-latest#june-4-2019
> chore(rootfs/Dockerfile): update az CLI to v2.0.66

- rootfs/Dockerfile
See https://github.com/Masterminds/glide/releases/tag/v0.13.3
> chore(rootfs/Dockerfile): update glide to v0.13.3

- rootfs/Dockerfile
See https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?view=azure-cli-latest#july-16-2019
> chore(rootfs/Dockerfile): update Azure CLI to v2.0.69

- rootfs/Dockerfile
See https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?view=azure-cli-latest#july-30-2019
> chore(rootfs/Dockerfile): update Azure CLI to v2.0.70

- rootfs/Dockerfile
> chore(rootfs/Dockerfile): update base to ubuntu:18.04

- rootfs/Dockerfile
See https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?view=azure-cli-latest#august-13-2019
> chore(rootfs/Dockerfile): update Azure CLI to v2.0.71

- rootfs/Dockerfile
See https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?view=azure-cli-latest#august-27-2019
> chore(rootfs/Dockerfile): update Azure CLI to v2.0.72

- rootfs/Dockerfile
See https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?view=azure-cli-latest#october-15-2019
> chore(rootfs/Dockerfile): update Azure CLI to v2.0.75

- rootfs/usr/local/bin/k
> fix: update k script from master

- rootfs/Dockerfile
Followed instructions at https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#latest-releases-via-apt-ubuntu
> feat(rootfs/Dockerfile): add ansible

- rootfs/Dockerfile
See https://golang.org/doc/devel/release.html#go1.13
> chore(rootfs/Dockerfile): update go toolchain to 1.13.5

- rootfs/Dockerfile
See https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?view=azure-cli-latest#november-26-2019
> chore(rootfs/Dockerfile): update Azure CLI to v2.0.77

- rootfs/Dockerfile
See https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?view=azure-cli-latest#january-07-2020
> chore(rootfs/Dockerfile): update Azure CLI to v2.0.79

- rootfs/Dockerfile
See https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?view=azure-cli-latest#january-13-2020
> chore(rootfs/Dockerfile): update Azure CLI to v2.0.80

- rootfs/Dockerfile
See https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/release-notes-azure-cli.md#february-18-2020
> chore(rootfs/Dockerfile): update Azure CLI to 2.1.0

- rootfs/Dockerfile
See https://golang.org/doc/go1.14
> chore(rootfs/Dockerfile): update go toolchain to 1.14

- rootfs/Dockerfile
See https://golang.org/doc/go1.14.1
> chore(rootfs/Dockerfile): update go toolchain to 1.14.1

- rootfs/Dockerfile
See https://github.com/mvdan/sh/releases/tag/v3.1.0
> chore(rootfs/Dockerfile): update shfmt to v3.1.0

- rootfs/Dockerfile
See https://github.com/mvdan/sh/releases/tag/v3.1.1
> chore(rootfs/Dockerfile): update shfmt to v3.1.1

- rootfs/Dockerfile
See https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?view=azure-cli-latest#june-02-2020
> chore(rootfs/Dockerfile): update Azure CLI to 2.7.0

- rootfs/Dockerfile
See https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?view=azure-cli-latest#july-14-2020
> chore(rootfs/Dockerfile): update Azure CLI to 2.9.0

- rootfs/Dockerfile
See https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?view=azure-cli-latest&tabs=azure-cli#july-16-2020
> chore(rootfs/Dockerfile): update Azure CLI to 2.9.1

- rootfs/Dockerfile
See https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?view=azure-cli-latest&tabs=azure-cli#august-11-2020
> chore(rootfs/Dockerfile): update Azure CLI to 2.10.1

- rootfs/Dockerfile
See https://golang.org/doc/go1.15
> chore(rootfs/Dockerfile): update go toolchain to 1.15

- rootfs/Dockerfile
See https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?tabs=azure-cli#september-29-2020
> chore(rootfs/Dockerfile): update Azure CLI to 2.12.1

- rootfs/Dockerfile
See https://github.com/golang/go/issues?q=milestone%3AGo1.15.3+label%3ACherryPickApproved
> chore(rootfs/Dockerfile): update go toolchain to 1.15.3

- rootfs/Dockerfile
Signed-off-by: Ernest Wong <chuwon@microsoft.com>
> chore(rootfs/Dockerfile): update Docker version to 20.10.2

- rootfs/Dockerfile
See https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?tabs=azure-cli#march-02-2021
> chore(rootfs/Dockerfile): update Azure CLI to 2.20.0

- rootfs/Dockerfile
See https://github.com/mvdan/sh/releases/tag/v3.2.2
> chore(rootfs/Dockerfile): update shfmt to v3.2.2

- rootfs/Dockerfile
See https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?tabs=azure-cli#april-19-2021
> chore(rootfs/Dockerfile): update Azure CLI to v2.22.1

- rootfs/Dockerfile
See https://github.com/mvdan/sh/releases/tag/v3.2.4
> chore(rootfs/Dockerfile): update shfmt to v3.2.4

- README.md
- rootfs/Dockerfile
See https://github.com/aelsabbahy/goss/releases/tag/v0.3.16
> feat(rootfs/Dockerfile): add goss tool for validating server configs

- rootfs/Dockerfile
update upx to latest v3.96
Closes: #292
> chore(rootfs/Dockerfile): bump UPX v3.96

- rootfs/Dockerfile
See https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?tabs=azure-cli#july-14-2021
> chore(rootfs/Dockerfile): update Azure CLI to v2.26.1

- rootfs/Dockerfile
> chore(rootfs/Dockerfile): install ansible 2.10.9

- rootfs/Dockerfile
See https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?tabs=azure-cli#august-23-2021
> chore(rootfs/Dockerfile): update Azure CLI to v2.27.2

- rootfs/Dockerfile
See https://github.com/golangci/golangci-lint/releases/tag/v1.44.0
> chore(rootfs/Dockerfile): update golangci-lint to v1.44.0

- rootfs/Dockerfile
This reverts commit a11f7edf62ea92a72ab7a169b5ab9932ea6f8a5a.
> revert: "chore(rootfs/Dockerfile): remove yq tool (#317)"

- rootfs/Dockerfile
See https://golang.org/doc/devel/release#go1.18.minor
> chore(rootfs/Dockerfile): update Go toolchain to v1.18.7
